{% set name = "dufte" %}
{% set version = "0.2.29" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dufte-{{ version }}.tar.gz
  sha256: 9177a09fb27d46fe5b1390825c9347ecddb5176b4fa69614ce0d83499c200689

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - matplotlib-base
    - numpy
    - python >={{ python_min }}

test:
  imports:
    - dufte
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/nschloe/dufte
  summary: Clean matplotlib plots
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - izahn
